project_id = "jidfganntquilvsytslp"

[functions.admin-api]
verify_jwt = false

[functions.google-routes]
verify_jwt = false

[functions.twilio-otp]
verify_jwt = false

[functions.import-osm-places]
verify_jwt = false

[functions.settle-trip]
verify_jwt = false

[functions.agora-token]
verify_jwt = false

[functions.google-maps-key]
verify_jwt = false
